name: '🚀 Feature Request'
description: 'Suggest a new feature or improvement'
title: '[Feature Request]: '
labels: ['enhancement']

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Why do you need this feature? What problem does it solve?
      placeholder: Problem Statement
    validations:
      required: true

  # Choose a package scope
  - type: dropdown
    id: scope
    attributes:
      label: Package Scope
      description: Which package is this issue related to?
      options:
        - Please select a package
        - enum-plus (core)
        - '@enum-plus/plugin-antd'
        - '@enum-plus/plugin-i18next'
        - '@enum-plus/plugin-react-i18next'
        - '@enum-plus/plugin-react'
        - '@enum-plus/plugin-i18next-vue'
        - '@enum-plus/plugin-vue-i18n'
        - '@enum-plus/plugin-angular'
        - '@enum-plus/plugin-next-international'
        - other
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe in detail the feature you'd like to see. Be as specific as possible
      placeholder: Please describe the feature in detail
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide some specific scenarios of how this feature would be used.
      placeholder: List specific use cases for this feature
    validations:
      required: true

  - type: textarea
    id: importance
    attributes:
      label: Importance
      description: Describe why this feature is important and its impact.
      placeholder: This feature will help us to ...
    validations:
      required: false

  - type: dropdown
    id: feature-level
    attributes:
      label: Feature Level
      description: |
        Please consider the generality of this feature. Should it be part of the `enum-plus` core library, or implemented as a plugin? If you recommend implementing it as a plugin, please further specify whether it should be added to the official ``enum-plus-plugin`` plugin library or released as an independent external plugin?
        - `Core Library`: This is a generic feature that is simple and has no external dependencies, and should be part of the `enum-plus` core library
        - `Official Plugin`: This may be a generic feature that applies to most scenarios, but is more complex or has external dependencies, and should be part of the `enum-plus-plugin` official plugin library
        - `External Plugin`: This may not be a generic feature, or only suitable for a specific scenario, and may not be suitable for the core library or official plugin library, and should be released as an independent plugin library
      options:
        - Please select
        - Core Library
        - Official Plugin
        - External Plugin
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution (Optional)
      description: If you have a specific solution in mind, please describe it here. 
      placeholder: Please describe your proposed solution, but don't worry if you can't
    validations:
      required: false
