name: 'Replace download urls'
description: 'Replace download URLs in README and README.zh-CN'
inputs:
  version:
    description: 'Version to use in URLs'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        sed -i -E "s~https://cdn.jsdelivr.net/npm/enum-plus@v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+\.[0-9]+)?/~https://cdn.jsdelivr.net/npm/enum-plus@${{ inputs.version }}/~g" README.md README.zh-CN.md
        sed -i -E "s~https://github.com/shijistar/enum-plus/releases/download/v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+\.[0-9]+)?/~https://github.com/shijistar/enum-plus/releases/download/${{ inputs.version }}/~g" README.md README.zh-CN.md
        sed -i -E "s~https://github.com/shijistar/enum-plus/releases/tag/v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+\.[0-9]+)?/~https://github.com/shijistar/enum-plus/releases/tag/${{ inputs.version }}/~g" README.md README.zh-CN.md
        sed -i -E "s~https://cdn.jsdelivr.net/gh/shijistar/enum-plus@v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+\.[0-9]+)?/~https://cdn.jsdelivr.net/gh/shijistar/enum-plus@${{ inputs.version }}/~g" README.md README.zh-CN.md
      shell: bash
