import { themes, type ThemeVars } from 'storybook/theming';

export const light: ThemeVars = {
  ...themes.light,
  base: 'light',
  brandTitle: 'ENUM-PLUS',
  brandUrl: 'https://github.com/shijistar/enum-plus',
  colorPrimary: '#0f766e',
  colorSecondary: '#0f8f83',
  appBg: '#eef7f5',
  appContentBg: 'transparent',
  appPreviewBg: '#f7fcfb',
  appHoverBg: '#e3f1ee',
  appBorderColor: '#cfe3df',
  appBorderRadius: 16,
  barBg: '#f7fcfb',
  barTextColor: '#4f6460',
  barSelectedColor: '#0f766e',
  barHoverColor: '#11433f',
  booleanBg: '#d8efea',
  booleanSelectedBg: '#0f766e',
  buttonBg: '#fcfefd',
  buttonBorder: '#cfe3df',
  fontBase: "'SF Pro Display', 'Segoe UI', 'PingFang SC', 'Helvetica Neue', Arial, sans-serif",
  fontCode: "'JetBrains Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
  inputBg: '#fbfefd',
  inputBorder: '#cfe3df',
  inputBorderRadius: 12,
  inputTextColor: '#1e3230',
  textColor: '#163836',
  textMutedColor: '#64817b',
  textInverseColor: '#f7fcfb',
};

export const dark: ThemeVars = {
  base: 'dark',
  brandTitle: 'ENUM-PLUS',
  brandUrl: 'https://github.com/shijistar/enum-plus',
  colorPrimary: '#3dd6c2',
  colorSecondary: '#f59e0b',
  appBg: '#0b1117',
  appContentBg: 'transparent',
  appPreviewBg: '#0f1720',
  appHoverBg: '#16232d',
  appBorderColor: '#223241',
  appBorderRadius: 16,
  barBg: '#101922',
  barTextColor: '#b7c3ca',
  barSelectedColor: '#3dd6c2',
  barHoverColor: '#e7ecef',
  booleanBg: '#173238',
  booleanSelectedBg: '#3dd6c2',
  buttonBg: '#111c26',
  buttonBorder: '#223241',
  fontBase: "'SF Pro Display', 'Segoe UI', 'PingFang SC', 'Helvetica Neue', Arial, sans-serif",
  fontCode: "'JetBrains Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace",
  inputBg: '#111c26',
  inputBorder: '#223241',
  inputBorderRadius: 12,
  inputTextColor: '#e7ecef',
  textColor: '#e7ecef',
  textMutedColor: '#8ea0ab',
  textInverseColor: '#0b1117',
};
