name: 🧪 Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      use-matrix: false
